version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/CaseManagement.Pn"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eFormBasicCaseManagementBase
    versions:
    - 2.0.102
    - 2.0.103
    - 2.0.110
    - 2.0.111
    - 2.0.112
    - 2.0.92
    - 2.0.95
    - 2.0.97
    - 2.1.1
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.100
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.104
    - 2.0.106
    - 2.0.108
    - 2.0.112
    - 2.0.122
    - 2.0.126
    - 2.0.127
    - 2.0.97
    - 2.1.2
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.4.1
    - 4.4.11
    - 4.4.14
    - 4.4.22
    - 4.4.31
    - 4.4.35
    - 4.4.36
    - 4.4.4
    - 4.4.6
    - 4.4.7
    - 4.4.9
    - 4.5.2
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
