//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManagement.Pn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CaseManagementPnResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaseManagementPnResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseManagement.Pn.Properties.CaseManagementPnResources", typeof(CaseManagementPnResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar user deleted successfully.
        /// </summary>
        internal static string CalendarUserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CalendarUserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar user has been created.
        /// </summary>
        internal static string CalendarUserHasBeenCreated {
            get {
                return ResourceManager.GetString("CalendarUserHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar user not found.
        /// </summary>
        internal static string CalendarUserNotFound {
            get {
                return ResourceManager.GetString("CalendarUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar user updated successfully.
        /// </summary>
        internal static string CalendarUserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("CalendarUserUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtaining calendar info.
        /// </summary>
        internal static string ErrorObtainingCalendarInfo {
            get {
                return ResourceManager.GetString("ErrorObtainingCalendarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating calendar user.
        /// </summary>
        internal static string ErrorWhileCreatingCalendarUser {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingCalendarUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting calendar user.
        /// </summary>
        internal static string ErrorWhileDeletingCalendarUser {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingCalendarUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtaining calendar user info.
        /// </summary>
        internal static string ErrorWhileObtainingCalendarUserInfo {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingCalendarUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtaining case management settings.
        /// </summary>
        internal static string ErrorWhileObtainingCaseManagementSettings {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingCaseManagementSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating calendar user.
        /// </summary>
        internal static string ErrorWhileUpdatingCalendarUser {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingCalendarUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating case management settings.
        /// </summary>
        internal static string ErrorWhileUpdatingCaseManagementSettings {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingCaseManagementSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings has been updated successfully.
        /// </summary>
        internal static string SettingsHasBeenUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsHasBeenUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
